apiVersion: v1
kind: Service
metadata:
  name: blackboxgameengine
  labels:
    name: blackboxgameengine    
spec:
  selector:
    name: blackboxgameengine    
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: blackboxgameengine
      targetPort: 80
      protocol: TCP
    - port: 81
      name: istio-proxy
      targetPort: 81
      protocol: TCP    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackboxgameengine
spec:
  replicas: 3
  selector:
    matchLabels:
      name: blackboxgameengine      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: blackboxgameengine        
    spec:
      containers:
      - name: blackboxgameengine
        image: ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamedayengine-web:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: gameengine
            protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env: 
          - name: "ConnectionStrings__GameEngineDB"
            value: "Server=tcp:game-sqlserver-e9cc7a.database.windows.net,1433;Initial Catalog=gamedb;Persist Security Info=False;User ID=gamedbadministrator;Password=l2y7sruELWN2m;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          - name: "ARCADE_BACKENDURL"
            value: "http://arcadebackend/pick"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "8e2e217a-5c3c-43ef-a618-0ea9f28ef6bb"
